site_name: Reproducible Sign Rates

theme:
    name: readthedocs

plugins:
- search
- mkdocstrings:
    handlers:
        python:
            options:
                show_root_heading: False
                show_source: False
                docstring_section_style: table

extra_css: [extra.css]

watch:
- reproduciblesignrates


extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js